### ISSUE TITLE
Feasibility

### ISSUE THREAD

**Issue by serkolch** [monsterpony/game-dots#1]

**Comment by serkolch** [comment]
@monsterpony 
Hey Heidi,

The idea looks good! I think it's well within the scope of what we've learned and what can be done in a short period of time. The key will be making this game your own - whether or not that's with cool effects or with clean design, that's up to you.

Good user stories and wireframe

**Comment by monsterpony** [comment]
Thank you for your feedback. I hope to make it functional AND super cool.
